using System;

namespace UmbracoTemplate.Logging
{
    /// <summary>
    /// Defines the logging options for this application
    /// </summary>
    public interface ILoggingService
    {
        /// <summary>
        /// Writes the diagnostic message for the default level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        void Log(string message);

        /// <summary>
        /// Writes the diagnostic message for the specified level
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="type">The log type.</param>
        void Log(string message, LogTypes type);

        /// <summary>
        /// Writes the diagnostic message at the Info level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="args">Additional formatting parameters</param>
        void Info(string message, params object[] args);

        /// <summary>
        /// Writes the diagnostic message at the Debug level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="args">Additional formatting parameters</param>
        void Debug(string message, params object[] args);

        /// <summary>
        /// Writes the diagnostic message at the Warning level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="args">Additional formatting parameters</param>
        void Warn(string message, params object[] args);

        /// <summary>
        /// Writes the diagnostic message at the Error level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="args">Additional formatting parameters</param>
        void Error(string message, params object[] args);

        /// <summary>
        /// Writes the diagnostic message at the Error level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="exception">Exception that was generated by the error</param>
        /// <param name="args">Additional formatting parameters</param>
        void Error(string message, Exception exception, params object[] args);

        /// <summary>
        /// Writes the diagnostic message at the Fatal level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="args">Additional formatting parameters</param>
        void Fatal(string message, params object[] args);

        /// <summary>
        /// Writes the diagnostic message at the Fatal level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="exception">Exception that was generated by the error</param>
        /// <param name="args">Additional formatting parameters</param>
        void Fatal(string message, Exception exception, params object[] args);
    }
}